### ISSUE TITLE
Connection class does not extend EventEmitter

### ISSUE THREAD

**Issue by eXeDK** [abreits/amqp-ts#11]
I'm unable to listen on events from the Connection class since the Connection class does not extend the EventEmitter eventhough the typings files states that the Connection does extend the EventEmitter, same does the sourcecode of amqplib (https://github.com/squaremo/amqp.node/blob/master/lib/connection.js#L56)

Should I create a pull request or could you fix it yourself? Should be a very quick fix.

Best Regards
Thomas

**Comment by abreits** [comment]
While it is true that the amqplib Connection class extends EventEmitter, the amqp-ts Connection does not, because it is not based on the amqplib Connection, it uses the amqplib Connection internally and exposes some elements of it when a successful connection has been made.

see: https://github.com/abreits/amqp-ts/blob/master/lib/amqp-ts.d.ts

It is possible to use the internal, not in amqp-ts.d.ts exposed reference to the amqplib (Connection._connection) to get access to the event emitter of the amqplib Connection.

see: https://github.com/abreits/amqp-ts/blob/master/src/amqp-ts.ts#L44

To redesign the amqp-ts Connection to extend EventEmitter (and also emit/ propagate amqplib Connection events) is possible, but I do not believe it is the quick fix you think it is. I think it needs to be designed as follows:
- extend Connection class form EventEmitter
- after a connection has been established forward all (relevant, subscribed, ...) amqplib Connection events to the amqp-ts event emitter
- make sure everything keeps functioning after a connection loss and reconnect 

I will put it on the backlog, but since other projects have priority now it could take a while to get implemented. However you are welcome to create a pull request. (I am still learning how to best deal with pull requests so please have some patience)

Best regards,
Ab

**Comment by eXeDK** [comment]
Thanks you for the quick and thorough answer Ab, I'll have a look at the internal _connection you mentioned. If that's not sufficient I'll look into a fix.

Have a great day
Thomas
