### ISSUE TITLE
The NPM published version is not JS

### ISSUE THREAD

**Issue by Narven** [abreits/amqp-ts#28]
The publish version of this library (on NPM) is not JS.

If we use this library... ts will try to compile... and it will break.. if you have a different version, from the one built, and this lib is kind of old.

When publishing to npm you should publish only the build version (js), **not** the ts files.

**Comment by abreits** [comment]
I am sorry that you state things without checking whether they are true, because the library is published as javascript (check the package.json). It is indeed an old version of typescript, but it still is typescript.

Just exclude typescript from compiling the amqp-ts .ts source code in node-modules and it should work.

**Comment by Narven** [comment]
Wow... sry. I'm completely stupid.. I was looking for the js file and did not found it :(

Thanks
