### ISSUE TITLE
How can I set prefetch option for a channel?

### ISSUE THREAD

**Issue by Beingbook** [abreits/amqp-ts#5]
I want to use `[prefetch](http://www.squaremobius.net/amqp.node/channel_api.html#channel_assertQueue)`.
API reference in this wiki looks forget the option.

**Comment by abreits** [comment]
I have not implemented these options because I had no need for them. I will add them to a future release. In the meantime you can use the hidden _channel property (undocumented and unsupported, see the source code for more details) of Queue you need it for this points to the AmqpLib.Channel.

You can use the following code (just make sure to ignore the typescript errors):

```typescript
      // execute sync when possible
      if (queue.initialized.isFulfilled()) {
        queue._channel.prefetch(amount);
      } else {
        queue.initialized.then(queue._channel.prefetch(amount););
      }
```

I have not tested this, so use at your own risk.

**Comment by Beingbook** [comment]
@abreits Thank you!
